[package]
name = "sat_rs"
version = "0.2.0"
authors = ["stefano <s.kouroupis@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys-info = "0.9.1"
regex = "1.12.3"
log = "0.4.29"
simplelog = "0.12.2"
